name: code-trigger
on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://sendposts.vercel.app/api/run'
